---
title: "Binning"
server: shiny
format:
  dashboard:
    theme: cosmo
    orientation: columns
    nav-buttons:
      - icon: github
        href: https://github.com/RobWiederstein/lifeExpectancy/tree/master
---
  
```{r setup}
#| context: setup
#| include: false
library(bslib)
library(bsicons)
library(classInt)
library(colorspace)
library(cowplot)
library(DT)
library(dplyr)
library(ggplot2)
library(htmltools)
library(magrittr)
library(sf)
library(scales)
library(shiny)
library(waiter)
ihme <- readRDS("./data/ihme.rds")
ihme_ts <- readRDS("./data/ts_ihme_by_race.rds")
cb_us <- readRDS("./data/cb_us.rds")
sb_us <- readRDS("./data/sb_us.rds")
method_description <- readRDS("./data/method_description.rds")
source("./R/functions.R")
```

# Inputs {.sidebar}

```{r}
useWaiter()
waiterOnBusy(html = spin_2(), color = "#e5e5e5", fadeout = 500)
h6("Inputs:")
hr()
selectInput(
  inputId = "year", 
  label = "Years", 
  choices = ihme$year %>% unique() %>% sort() %>% rev(),
  selected = max(ihme$year)
)
selectInput(
  inputId = "gender", 
  label = "Gender:", 
  choices = ihme$sex_name %>% unique() %>% sort(),
  selected = "Both"
)
selectInput(
  inputId = "race",
  label = "Race:",
  choices = list("Total" = "Total", "American Indian / Alaskan Native" = "AIAN", "Asian Pacific Islander" = "API", "Black" = "Black", "Latino" = "Latino", "White" = "White"),
  selected = "Total"
)
selectInput(
  inputId = "bins",
  label = "Bins:",
  choices = c(4:9),
  selected = 4
)
selectInput(
  inputId = "method",
  label = "Method:",
  choices = c("bclust", "box", "dpih", "equal", "fisher", "fixed", "hclust", 
"headtails", "jenks", "kmeans", "maximum", "pretty", "quantile", 
"sd"),
  selected = "fisher"
)
selectInput(
  inputId = "type",
  label = "Type:",
  choices = c("diverging", "sequential"),
  selected = "sequential"
)
selectInput(
  inputId = "palette",
  label = "Palette:",
  choices = NULL,
  selected = NULL
)
selectInput(
  inputId = "reverse",
  label = "Reverse:",
  choices = c("False", "True"),
  selected = "True"
)
selectInput(
  inputId = "keep_ol",
  label = "Keep Outliers:",
  choices = c(FALSE, TRUE),
  selected = TRUE
)
selectInput(
  inputId = "overlay", 
  label = "Overlay:",
  choices = list(
    "U.S. States" = "states",
    "None" = "none"
    ),
  selected = "none"
)
selectInput(
    inputId = "border",
    label = "Border Color:",
    choices = paste0("gray", seq(0, 100, by = 25))
  )
downloadButton('downloadPlot', 'Download Plot')
```

```{r server}
#| context: server

observeEvent(input$type, {
  freezeReactiveValue(input, "palette")
  colors <- hcl_palettes(type = input$type) %>% 
    row.names() %>% sort() %>% dput()
  updateSelectInput(inputId = "palette", choices = colors)
})
 
label_title <- reactive({
  ifelse(input$year == "2019", "Life Expectancy", "Change in Life \nExpectancy")
})

ihme_filtered <- reactive({
  filter_ihme(
    input_year      = input$year, 
    input_sex       = input$gender, 
    input_race      = input$race, 
    input_keep_ol   = input$keep_ol,
    input_bins      = input$bins,
    input_method    = input$method,
    input_dataset   = ihme
  )
})
terr_filtered <- reactive({
  if(input$overlay == "states"){
    sb_us
    }else{
      if(input$overlay == "none"){
        "None"
      }
    }
})

us_map <- reactive({
   map_us_data(
    input_year     = input$year,
    input_sex      = input$gender,
    input_race     = input$race,
    input_type     = input$type,
    input_palette  = input$palette,
    input_reverse  = input$reverse,
    input_title    = label_title(),
    input_dataset  = ihme_filtered(),
    input_poly     = cb_us,
    input_overlay  = terr_filtered(),
    input_border   = input$border
  )
})

output$map <- renderPlot({
 us_map()
})

output$table <- renderDT({
  datatable(
    map_us_data_tbl(
    input_bins    = input$bins,
    input_method  = input$method,
    input_dataset = ihme_filtered()
    ),
  rownames = F,
  options = list(list("val", "desc"), dom = "ft")
  ) %>% 
    formatRound("val", digits = 1)
})

output$histogram <- renderPlot({
  histogram_life_exp(
    input_year     = input$year,
    input_race     = input$race,
    input_sex      = input$gender,
    input_bins     = input$bins,
    input_method   = input$method,
    input_type     = input$type,
    input_palette  = input$palette,
    input_reverse  = input$reverse,
    input_dataset  = ihme_filtered(),
    input_title    = label_title()
  )
})

output$overall_title <- renderText({
  paste("Avg.", input$race,  label_title(), input$year)
})

output$overall_gender <- renderText({
  paste("Gender: ", input$gender)
})

output$overall <- renderText({
  pull_avg_overall_life_exp(
    input_year = input$year,
    input_sex  = input$gender,
    input_race = input$race,
    input_keep_ol = input$keep_ol,
    input_dataset = ihme
    )
})

output$ts <- renderPlot({
 ts_avg_life_exp(
   input_year = as.integer(input$year),
   input_race = input$race,
   input_keep_ol = input$keep_ol,
   input_dataset = ihme_ts
   )
})

output$n_counties <- renderText({
  pull_number_of_counties(
    input_race    = input$race,
    input_year    = input$year,
    input_sex     = input$gender,
    input_keep_ol = input$keep_ol,
    dataset       = ihme
  )
})

output$method_desc <- renderTable({
  show_method_description(
    input_method = input$method,
    input_dataset = method_description
  )
})

output$downloadPlot <- downloadHandler(
    filename <- "us_map.png",
    content = function(file, width = 8, height = 6) {
        ggsave(us_map(), width = width, height = height, 
               units = "in", filename = file)
    }
)
```


# Life Expectancy {orientation="rows"}

## row {height=65%}

### column {.tabset width=65%}

::: {.card title="Map"}

```{r}

plotOutput("map")

```

:::

::: {.card title="Table"}

```{r}
DTOutput("table")
```

:::

### column {.tabset}

::: {.card title="Histogram"}

```{r}

plotOutput("histogram")

```

:::

::: {.card title="Method"}

```{r}
tableOutput("method_desc")
```

:::

## row {height=35%}


```{r}
value_box(
  id = "Card 1",
  title = textOutput("overall_title"),
  value = textOutput("overall"),
  showcase = bs_icon("cake2"),
  theme = "light",
  p(textOutput("overall_gender"))
)

```


```{r}
plotOutput("ts")
```

```{r}
value_box(
  id = "Card 2",
  title = "Number of Counties: ",
  value = textOutput("n_counties"),
  showcase = bs_icon("pin-map-fill"),
  theme = "light",
  p("out of 3,144 total counties.")
)
```

<!--

# Inputs

```{r}
tableOutput("proj_inputs")
```


```{r}
#| context: server
output$proj_inputs <- renderTable({
  tibble::tribble(
    ~'variable',                   ~"output",               ~"description",
    "input$year",                input$year,                "calendar year as string",
    "input$gender",              input$gender,              "gender",
    "input$race",                input$race,                "race",
    "input$bins",                input$bins,                "number of bins",
    "input$method",              input$method,              "algorithm to bin life expectancy",
    "input$type",                input$type,                "palette type",
    "input$palette",             input$palette,             "palette colors",
    "input$reverse",             input$reverse,             "reverse order of color palette",
    "input$keep_ol",             input$keep_ol,             "map with or without outliers",
    "input$overlay",             input$overlay,             "overlay areas",
    "input$border",              input$border,              "gray scale for state borders"
  )
})

```


-->